### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by bharatmourya** [p-durlej/newsys#3]
> bharat@Bharat:~/os386/src$ ARCH=amd64 s/mkrelse
> gmake[2]: /home/bharat/os386/src/../tools/bin/amd64-os386-elf-gcc: Command not found
> Makefile:35: recipe for target 'fdboot.bin' failed
> gmake[2]: *** [fdboot.bin] Error 127
> mk/main.mk:39: recipe for target 'all' failed
> gmake[1]: *** [all] Error 2
> Makefile:35: recipe for target 'all' failed
> gmake: *** [all] Error 2

Hi, I am trying to compile from source but facing this error,  all I did is  's/mkall' and 's/mkrelse'. I facing the error on run s/mkrelse. I checked if I have amd64-os386-elf-gcc in tools/bin after s/mkall and I don't have amd64 gcc  and also i386 gcc.

I might be missing something trivial, please help.

**Comment by p-durlej** [comment]
What's the build host OS, OS version and cpu architecture?

**Comment by Revengegm** [comment]
Hello,
Same on Ubuntu 16.04.5 x64 unfortunately :( Seems like I'm doing something wrong, but all I did is 's/mkall' after tried 's/mkrelse' aaand same error.

**Comment by p-durlej** [comment]
Hello,

as a workaround you may want to try rebuilding under OpenBSD 6.2/amd64. A VM will do.

The use of the outdated OpenBSD version aims to reproduce the build environment of the last release of Vanadium OS.
